/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

/**
 *
 * @author serpi
 */
public class AgregarCarrito extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCarrito
     */
    public AgregarCarrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnComprarAhora = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblFoto.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(0, 0, 0));
        lblFoto.setText("jLabel2");
        lblFoto.setOpaque(true);
        add(lblFoto);
        lblFoto.setBounds(210, 50, 460, 380);

        btnMenos.setText("jButton1");
        add(btnMenos);
        btnMenos.setBounds(860, 360, 50, 32);

        btnMas.setText("jButton2");
        add(btnMas);
        btnMas.setBounds(1065, 360, 50, 32);

        btnComprarAhora.setText("jButton3");
        add(btnComprarAhora);
        btnComprarAhora.setBounds(1040, 440, 77, 32);

        btnAgregar.setText("jButton4");
        add(btnAgregar);
        btnAgregar.setBounds(860, 440, 77, 32);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("jLabel6");
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(940, 360, 100, 32);

        lblNombre.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("jLabel3");
        lblNombre.setOpaque(true);
        add(lblNombre);
        lblNombre.setBounds(780, 50, 260, 50);

        lblPrecio.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("jLabel4");
        lblPrecio.setOpaque(true);
        add(lblPrecio);
        lblPrecio.setBounds(1060, 50, 140, 50);

        lblInfo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("jLabel5");
        lblInfo.setOpaque(true);
        add(lblInfo);
        lblInfo.setBounds(780, 120, 420, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuRoles/PANEL PRINCIPAL.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -150, 1380, 770);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnComprarAhora;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    // End of variables declaration//GEN-END:variables
}
