/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Tablas.Empleados;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import EnumClases.TipoEmpleado;

/**
 *
 * @author serpi
 */
public class GestionarEmpleados extends javax.swing.JPanel {
    
    ArrayList<Empleados> empleados;
    DefaultListModel modeloEmpleados = new DefaultListModel();
    
    TipoEmpleado tipoEmpleado;
    
    
    public GestionarEmpleados() {
        initComponents();
        
        jlListaEmpleados.setModel(modeloEmpleados);
        
        for(TipoEmpleado tipo : tipoEmpleado.values()){
            cbTiposEmpleados.addItem(tipo.toString());
        }
        
        
        empleados = RestauranteConexion.RestauranteService.mostrarEmpleadosService();
        
        for(int i = 0; i < empleados.size(); i++){
            if(empleados.get(i).getEmp_Tipo().getTipo_Id() == 1)
            modeloEmpleados.addElement(empleados.get(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTiposEmpleados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListaEmpleados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbApellidoP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbFechaNacimiento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        cbTiposEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTiposEmpleadosMouseClicked(evt);
            }
        });
        cbTiposEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTiposEmpleadosActionPerformed(evt);
            }
        });
        add(cbTiposEmpleados);
        cbTiposEmpleados.setBounds(160, 90, 140, 40);

        jlListaEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlListaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlListaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlListaEmpleados);

        add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 170, 210);

        jLabel2.setText("Nombre");
        add(jLabel2);
        jLabel2.setBounds(510, 70, 80, 60);

        jLabel3.setText("Apellido Paterno");
        add(jLabel3);
        jLabel3.setBounds(510, 140, 120, 16);

        lbApellidoP.setText("jLabel4");
        add(lbApellidoP);
        lbApellidoP.setBounds(630, 140, 41, 16);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(630, 190, 100, 16);

        jLabel6.setText("Apellido Materno");
        add(jLabel6);
        jLabel6.setBounds(510, 180, 120, 30);

        lbNombre.setText("jLabel7");
        add(lbNombre);
        lbNombre.setBounds(580, 80, 290, 30);

        jLabel8.setText("Fecha de nacimiento");
        add(jLabel8);
        jLabel8.setBounds(510, 230, 130, 16);

        lbFechaNacimiento.setText("jLabel4");
        add(lbFechaNacimiento);
        lbFechaNacimiento.setBounds(650, 220, 150, 30);

        jLabel9.setText("Tipo");
        add(jLabel9);
        jLabel9.setBounds(510, 320, 170, 20);

        jLabel10.setText("Sueldo");
        add(jLabel10);
        jLabel10.setBounds(510, 270, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuRoles/PANEL PRINCIPAL.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -140, 1670, 770);

        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(510, 370, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTiposEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTiposEmpleadosActionPerformed
        try {
            if(cbTiposEmpleados.getSelectedIndex() == 0){
            actualizarLista(1);
        }else if(cbTiposEmpleados.getSelectedIndex() == 1){
             actualizarLista(2);
        }else if(cbTiposEmpleados.getSelectedIndex() == 2){
             actualizarLista(3);
        }else if(cbTiposEmpleados.getSelectedIndex() == 3){
             actualizarLista(4);
        }else if(cbTiposEmpleados.getSelectedIndex() == 4){
             actualizarLista(5);
        }else{
            actualizarLista(6);
        }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_cbTiposEmpleadosActionPerformed

    private void cbTiposEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTiposEmpleadosMouseClicked
        
    }//GEN-LAST:event_cbTiposEmpleadosMouseClicked

    private void jlListaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlListaEmpleadosMouseClicked
        
    }//GEN-LAST:event_jlListaEmpleadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTiposEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlListaEmpleados;
    private javax.swing.JLabel lbApellidoP;
    private javax.swing.JLabel lbFechaNacimiento;
    private javax.swing.JLabel lbNombre;
    // End of variables declaration//GEN-END:variables

    private void actualizarLista(int tipo) {
        modeloEmpleados.removeAllElements();
        for(int i = 0; i < empleados.size(); i++){
            if(empleados.get(i).getEmp_Tipo().getTipo_Id() == tipo)
            modeloEmpleados.addElement(empleados.get(i));
        }
    }
}
